//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.CommServer.UA.ConfigurationEditor.ServerConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.CommServer.UA.ConfigurationEditor.ServerConfiguration.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was problem during opening the configuration form file:
        ///{0}
        ///Application will continue but the configuration is default..
        /// </summary>
        internal static string CASConfiguration_MessageBox_configuration_file_exception {
            get {
                return ResourceManager.GetString("CASConfiguration_MessageBox_configuration_file_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was problem during saving the configuration form file:
        ///{0}
        ///Application will continue but the configuration is default..
        /// </summary>
        internal static string CASConfiguration_MessageBox_configuration_file_save_exception {
            get {
                return ResourceManager.GetString("CASConfiguration_MessageBox_configuration_file_save_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was problem during opening the configuration form application internals
        ///{0}
        ///Application will continue but the configuration is default..
        /// </summary>
        internal static string CASConfiguration_MessageBox_configuration_internal_exception {
            get {
                return ResourceManager.GetString("CASConfiguration_MessageBox_configuration_internal_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS Plugin Configuration.
        /// </summary>
        internal static string CASConfiguration_MessageBox_title {
            get {
                return ResourceManager.GetString("CASConfiguration_MessageBox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open configuration file {0} (reason: {1})..
        /// </summary>
        internal static string CASConfiguration_UnableToOpenConfigurationFile {
            get {
                return ResourceManager.GetString("CASConfiguration_UnableToOpenConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS.UAServer.Configuration.
        /// </summary>
        internal static string Default_ConfigurationFileName {
            get {
                return ResourceManager.GetString("Default_ConfigurationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uasconfig.
        /// </summary>
        internal static string DefaultConfigurationFileNametExtension {
            get {
                return ResourceManager.GetString("DefaultConfigurationFileNametExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/DataPorter/Index.aspx.
        /// </summary>
        internal static string Help_MainPage {
            get {
                return ResourceManager.GetString("Help_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} is saved..
        /// </summary>
        internal static string InformationFileSaved {
            get {
                return ResourceManager.GetString("InformationFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.Configuration.xml.
        /// </summary>
        internal static string Main_Default_ConfigurationFileName {
            get {
                return ResourceManager.GetString("Main_Default_ConfigurationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS UA Server Configuration File Editor.
        /// </summary>
        internal static string MainEditorTitle {
            get {
                return ResourceManager.GetString("MainEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tags in the CommServer configuration file. Choose another file.
        /// </summary>
        internal static string NoTagsInTheCommServerConfiguration {
            get {
                return ResourceManager.GetString("NoTagsInTheCommServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommServer Configuration File Open Error.
        /// </summary>
        internal static string SessionFileOpenError {
            get {
                return ResourceManager.GetString("SessionFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution is not saved.
        /// </summary>
        internal static string SolutionIsNotSaved_Header {
            get {
                return ResourceManager.GetString("SolutionIsNotSaved_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution is not saved so the configuration file has been saved in the default location:.
        /// </summary>
        internal static string SolutionIsNotSaved_Info {
            get {
                return ResourceManager.GetString("SolutionIsNotSaved_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string SplitSignForCommServerTag {
            get {
                return ResourceManager.GetString("SplitSignForCommServerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tag_element_48_full {
            get {
                object obj = ResourceManager.GetObject("tag_element_48_full", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
