// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UAOOI.ConfigurationEditorUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Start empty window
        /// </summary>
        public void StartTestApplication()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UICVSProjectsCommServeWindow.UIItemWindow.UICASCommServerUAOOICoListItem.UINameEdit;
            WinButton uICloseButton = this.UIItemWindow.UICloseButton;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(124, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(16, 7));
        }
        
        #region Properties
        public UICVSProjectsCommServeWindow UICVSProjectsCommServeWindow
        {
            get
            {
                if ((this.mUICVSProjectsCommServeWindow == null))
                {
                    this.mUICVSProjectsCommServeWindow = new UICVSProjectsCommServeWindow();
                }
                return this.mUICVSProjectsCommServeWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICVSProjectsCommServeWindow mUICVSProjectsCommServeWindow;
        
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICVSProjectsCommServeWindow : WinWindow
    {
        
        public UICVSProjectsCommServeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "C:\\VS\\Projects\\CommServer.UA.ModelDesigner\\PR32-ModelDesigner\\UAOOI.Configuration" +
                "Editor.UITestA";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("C:\\VS\\Projects\\CommServer.UA.ModelDesigner\\PR32-ModelDesigner\\UAOOI.Configuration" +
                    "Editor.UITestA");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("C:\\VS\\Projects\\CommServer.UA.ModelDesigner\\PR32-ModelDesigner\\UAOOI.Configuration" +
                    "Editor.UITestA");
            #endregion
        }
        
        #region Properties
        public UICASCommServerUAOOICoListItem UICASCommServerUAOOICoListItem
        {
            get
            {
                if ((this.mUICASCommServerUAOOICoListItem == null))
                {
                    this.mUICASCommServerUAOOICoListItem = new UICASCommServerUAOOICoListItem(this);
                }
                return this.mUICASCommServerUAOOICoListItem;
            }
        }
        #endregion
        
        #region Fields
        private UICASCommServerUAOOICoListItem mUICASCommServerUAOOICoListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICASCommServerUAOOICoListItem : WinListItem
    {
        
        public UICASCommServerUAOOICoListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "CAS.CommServer.UAOOI.ConfigurationEditor.UITestApplication.exe";
            this.WindowTitles.Add("C:\\VS\\Projects\\CommServer.UA.ModelDesigner\\PR32-ModelDesigner\\UAOOI.Configuration" +
                    "Editor.UITestA");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("C:\\VS\\Projects\\CommServer.UA.ModelDesigner\\PR32-ModelDesigner\\UAOOI.Configuration" +
                            "Editor.UITestA");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
